name: news_app_hydroneo
description: Test app development for HydroNeo. News App.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.17
  # can use http package as well, but dio for more control.
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  provider: ^6.0.2
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  # date time format package
  intl: ^0.17.0
  pretty_dio_logger: ^1.1.1
  # bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  sensors_plus: ^1.2.1
  http: ^0.13.4
  bloc_test: ^9.0.2
  mockito: ^5.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  # hive generators for adapters - dependency of hive
  hive_generator: ^1.1.1
  build_runner: ^2.1.7
  html: ^0.15.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/.env

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/proxima_nova.ttf
    - family: Shoguns Clan
      fonts:
        - asset: assets/fonts/Shoguns_Clan.ttf
